### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by ghost** [gippy/kickstarter-search#8]
Apify worked like a charm yesterday. No such luck today.
`2021-03-03T17:00:39.645Z ACTOR: Pulling Docker image from repository.

2021-03-03T17:00:40.344Z ACTOR: Creating Docker container.
2021-03-03T17:00:42.415Z ACTOR: Starting Docker container.
2021-03-03T17:00:46.480Z INFO  System info {"apifyVersion":"0.21.11","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.4"}
2021-03-03T17:00:46.768Z Loading projects for query:
2021-03-03T17:00:46.775Z { category_id: 34, state: 'successful', sort: 'newest', page: 1 }
2021-03-03T17:00:47.080Z Page 1: Loading projects
2021-03-03T17:00:46.733Z Page 1: Found undefined projects
2021-03-03T17:00:46.735Z ERROR The function passed to Apify.main() threw an exception:
2021-03-03T17:00:46.736Z   TypeError: Cannot read property 'slice' of undefined
2021-03-03T17:00:46.736Z       at getProjects (/usr/src/app/src/getProjects.js:179:46)
2021-03-03T17:00:46.736Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-03T17:00:46.737Z       at async /usr/src/app/main.js:7:5
2021-03-03T17:00:46.737Z       at async run (/usr/src/app/node_modules/apify/build/actor.js:194:13)`

**Comment by ghost** [comment]
I fear that even the Apify proxy encounters the "are you human" page.

**Comment by pocesar** [comment]
@e1prime thanks for the report, unfortunately this scraper uses really old code, and currently deserves a major rewrite to be up par to other open source Apify scrapers

**Comment by vinceHq** [comment]
Hello, 

Getting the same error today whereas it was working on wednesday. 

Does someone have some tips and tricks to make it work back ?

**Comment by zpelechova** [comment]
Hey, @e1prime , it should be working smoothly now.
